# Site settings
title: TimeLess
icon:	/images/site.ico
email: mr_jianlong@hotmail.com
#description: Front-end Dev
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  mrzjl

# Build settings
#markdown: kramdown
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
#   ,"html_toc"
  ]

paginate: 5
paginate_path: "pages/:num"

imgrepo: "http://mrzjl.github.io/images/img"
images: "http://mrzjl.github.io/images/"





